### ISSUE TITLE
install errors for georasters 0.5.3 on macos 10.12.2 

### ISSUE THREAD

**Issue by impactanalysts** [ozak/georasters#16]
I tried installing georasters 0.5.3 for Python 2.7, in a virtual environment on macos 10.12.2. I tried installing with pip, but got the same errors regardless of which package repo I used:

    pip install georasters
    pip install git+git://github.com/ozak/georasters.git

In both cases, `setup.py` seemed to proceed normally, until I got these build errors associated with the 'pyproj._proj' extension.  FYI "geospatial_py2" is the name of the env:

    src/pj_fwd3d.c:6:2: error: unknown type name 'XYZ'; did you mean 'XY'?
              XYZ /* forward projection entry */
              ^~~
              XY
      /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:155:37: note: 'XY' declared here
      typedef struct { double x, y; }     XY;
                                          ^
      src/pj_fwd3d.c:7:10: error: unknown type name 'LPZ'; did you mean 'LP'?
      pj_fwd3d(LPZ lpz, PJ *P) {
               ^~~
               LP
      /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:156:37: note: 'LP' declared here
      typedef struct { double lam, phi; } LP;
                                          ^
      src/pj_fwd3d.c:8:2: error: unknown type name 'XYZ'; did you mean 'XY'?
              XYZ xyz;
              ^~~
              XY
      /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:155:37: note: 'XY' declared here
      typedef struct { double x, y; }     XY;
                                          ^
      src/pj_fwd3d.c:13:23: error: no member named 'z' in 'XY'
                      xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                      ~~~ ^
      src/pj_fwd3d.c:29:24: error: no member named 'fwd3d' in 'struct PJconsts'
                      if (P->fwd3d != NULL)
                          ~  ^
      src/pj_fwd3d.c:31:18: error: no member named 'fwd3d' in 'struct PJconsts'
                          xyz = (*P->fwd3d)(lpz, P); /* project */
                                  ~  ^
      src/pj_fwd3d.c:33:24: error: no member named 'z' in 'XY'
                              xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                              ~~~ ^
      src/pj_fwd3d.c:43:41: error: no member named 'z' in 'XY'
                          xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                          ~~~ ^
      8 errors generated.
      error: command 'gcc' failed with exit status 1
         ----------------------------------------
     Command "/Users/Mike/anaconda/envs/geospatial_py2/bin/python -u -c "import setuptools,   tokenize;__file__='/private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-build-IqbSaQ/pyproj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-SpvZBh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-build-IqbSaQ/pyproj/
      
I've attached the complete output of setup.py as a txt file: 
[georasters install errors.txt](https://github.com/ozak/georasters/files/673326/georasters.install.errors.txt)
Based on the above errors, is there a problem in the source code for pyproj? Can you help?

Please let me know what you think. Any advice you can give toward getting georasters installed on OSX would be much appreciated.

Mike

**Comment by ozak** [comment]
@impactanalysts it seems this is an issue with one of the dependencies ``pyproj`` not with ``georasters`` itself. Not sure why you are getting this, since I do not have any issues installing using ``conda`` with older versions of OS X, and the build is passing on Travis (which uses Linux and conda). I do not have access to a machine with Sierra at the moment, so I cannot tell if it is an OSX 10.12 issue. 

Can you try and ``conda install proj4`` itself and see what happens?  If that does not work then this issue needs to be raised with the ``pyproj`` or ``conda`` people upstream. 

Let me know if it worked.

**Comment by impactanalysts** [comment]
@ozak , thanks for looking at this. I already had `proj4` installed, so running the install command returned:

    # All requested packages already installed
    # packages in environment at /Users/Mike/anaconda/envs/geospatial_py2:
    #
    proj4                     4.9.2                         0    http://repo.continuum.io/pkgs/free/osx-64/proj4-4.9.2-  0.tar.bz2

Should I still raise an issue at `pyproj` site?

**Comment by ozak** [comment]
@impactanalysts were you able to install ``gegeorasters``? It is strange that ``pip`` was trying to install a package that was already installed on your system.

**Comment by ozak** [comment]
@impactanalysts it definitely seems to be a ``pyproj`` issue. I am getting a similar error when trying to install on OS X 10.12. Although the issue seems to be related to ``pyproj-1.9.5.1`` since ``pyproj-1.9.4`` works fine. I will raise the issue with them and see what they say.

**Comment by ozak** [comment]
@impactanalysts I checked and it is an issue with GDAL, since different packages seem to be using different versions. I have uploaded  [try_georasters.yml](https://github.com/ozak/georasters/blob/master/try_georasters.yml), which provides a working environment using ``conda``. Give it a try and let me know if it works.

**Comment by impactanalysts** [comment]
@ozak: re they ml file: when I click on the link, I get a 404 error.

**Comment by ozak** [comment]
sorry I changed the name of the file and forgot to change it here

**Comment by impactanalysts** [comment]
Got it, thanks!
