### ISSUE TITLE
Aggregate/Align example

### ISSUE THREAD

**Issue by apiszcz** [ozak/georasters#18]
I am attempting to perform the following
1. Reduce cell size by a factor of 10
2. Align two images with different extents
3. Ideally SUM values of each
4. I am getting a broadcast error stating the images are not equivalent in size.
5. I am unsure how the alignment return values are used.

```
f1='file1.tif'
f2='file2.tif'

data1t=gr.load_tiff(f1)
data2t=gr.load_tiff(f2)

NDV, xsize, ysize, GeoT, Projection, DataType = gr.get_geo_info(f1)
data1ta=gr.aggregate(data1t,NDV,(10,10))
data2ta=gr.aggregate(data2t,NDV,(10,10))

driver = gdal.GetDriverByName('GTiff')
driver.Register()
NoDataValue=0.0
GeoT=list(GeoT)
GeoT[1]=GeoT[1]*10
GeoT[5]=GeoT[5]*10

d1fname=gr.create_geotiff('test1d',data1ta,driver,NoDataValue,data1ta.shape[1], data1ta.shape[0], GeoT, Projection, DataType)
d2fname=gr.create_geotiff('test2d',data2ta,driver,NoDataValue,data2ta.shape[1], data2ta.shape[0], GeoT, Projection, DataType)

# Agregate raster by summing over cells in order to increase pixel size by e.g. 10
(alignedraster_o, alignedraster_a, GeoT_a) = gr.align_rasters(d1fname, d2fname, how=np.sum)

data1t=gr.load_tiff('test1d.tif')
data2t=gr.load_tiff('test2d.tif')

A=gr.GeoRaster(data1t, GeoT, nodata_value=NDV)
NDV, xsize, ysize, GeoT, Projection, DataType = gr.get_geo_info('test1d.tif')
A.projection=Projection
B=gr.GeoRaster(data2t, GeoT, nodata_value=NDV)
B.projection=Projection
C=B.merge(A)

mergedname=gr.create_geotiff('test_merged',C,driver,NoDataValue,alignedraster_o.shape[1], alignedraster_o.shape[0], GeoT_a, Projection, DataType
```

`ValueError: operands could not be broadcast together with shapes (138,166) (138,166) (118,166)`

**Comment by ozak** [comment]
@apiszcz I am not sure if I misunderstand or if what you were trying to do is not in the code you wrote. 

1. Reduce cell size by a factor of 10: Do you mean you want to decrease the number of cells by 10 or the actual cell size? the ``aggregate`` function is intended for the first, not the second. I am not the other can be performed with the current functions. 

2. Align two images with different extents: You should be getting the two rasters aligned with the command ``(alignedraster_o, alignedraster_a) = data1t.align(data1t, how=np.sum)`` if you intend to sum the cells otherwise choose the function of how you would like to treat the cells.

3. Ideally SUM values of each: Do you mean ``alignedraster_o + alignedraster_a``? Or summing the cells? See 2.

Let me know if this helps. Otherwise can you share the rasters and a clearer description of what you are trying to accomplish.

**Comment by apiszcz** [comment]
1. they are 10 meters i want them to be 100 meters (approx).
2. ok, that is whay I used
3. i want to get the result of the sum, ... I may have issues following the example.
4. I am trying to emulate the ESRI mosaic with SUM capability on images with different extents.
5. the sizes after the alin
```
(Pdb) aro.shape
(118, 151)
(Pdb) ara.shape
(138, 166)
```

**Comment by ozak** [comment]
Can you share the files so I can take a look at what is going on?

**Comment by apiszcz** [comment]
Input: f1.tif, f2.tif
Output: result.tif
Intermediate images attached: f1rr.tif, f2rr.tif
Images attached.

[georaster_test.zip](https://github.com/ozak/georasters/files/819324/georaster_test.zip)

**Comment by apiszcz** [comment]
Issues: Possible datatype, and definitely alignment use must be incorrect. So I left off the alignment, looking for any advice. Thanks.


```
f1=r'f1.tif'
f2=r'f2.tif'

NDV1, xsize1, ysize1, GeoT1, Projection1, DataType1 = gr.get_geo_info(f1)
NDV2, xsize2, ysize2, GeoT2, Projection2, DataType2 = gr.get_geo_info(f2)

data1t=gr.load_tiff(f1)
data2t=gr.load_tiff(f2)
f1a=gr.aggregate(data1t,NDV1,(10,10))
f2a=gr.aggregate(data2t,NDV2,(10,10))
NewDataType=gdal.GDT_Int32

driver = gdal.GetDriverByName('GTiff')
driver.Register()
NoDataValue=0.0

GeoT_1=list(GeoT1)
GeoT_1[1]=GeoT1[1]*10
GeoT_1[5]=GeoT1[5]*10

GeoT_2=list(GeoT2)
GeoT_2[1]=GeoT2[1]*10
GeoT_2[5]=GeoT2[5]*10

d1fname=gr.create_geotiff('f1rr',f1a,driver,NoDataValue,f1a.shape[1],f1a.shape[0],GeoT_1,Projection1,NewDataType)
d2fname=gr.create_geotiff('f2rr',f2a,driver,NoDataValue,f2a.shape[1],f2a.shape[0],GeoT_2,Projection2,NewDataType)
```

**Comment by apiszcz** [comment]
TX

How do I add a projection?

**Comment by ozak** [comment]
You could use ``osr`` and one of the methods there. E.g. I think the following would work, if your data is in WGS84 projection

    import osr
    f1.projection = osr.SpatialReference(osr.SRS_WKT_WGS84)

**Comment by apiszcz** [comment]
Thank you for the assistance, georasters, I hope to test this on some
larger data collections.

**Comment by apiszcz** [comment]
Another issue was setting the output type DataType to GDT_Int32 so the SUM
does not overflow the input 8 bit datatype

**Comment by apiszcz** [comment]
f1=r'gr/f1.tif'
f2=r'gr/f2.tif'

f1 = gr.from_file(f1)
f2 = gr.from_file(f2)

f1.nodata_value = -9
f2.nodata_value = -9

f1a = f1.aggregate((10,10))
f2a = f2.aggregate((10,10))

funion = f1a.union(f2a)
f1n = funion.copy()
f2n = funion.copy()
f1n.raster = np.ma.MaskedArray(np.ones_like(funion.raster.data)*f1.nodata_value, mask=True)
f2n.raster = np.ma.MaskedArray(np.ones_like(funion.raster.data)*f2.nodata_value, mask=True)
f1n = f1n.union(f1a)
f2n = f2n.union(f2a)
fsum = f1n + f2n
fsum.datatype=gdal.GDT_Int32
ffinal = funion.union(fsum)
ffinal.projection = osr.SpatialReference(osr.SRS_WKT_WGS84)
ffinal.to_tiff('result')
