### ISSUE TITLE
matplotlib complains under virtualenv

### ISSUE THREAD

**Issue by DeoLeung** [ozak/georasters#19]
```python
import georasters as gr

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

currently work around
```
import matplotlib
matplotlib.use('TkAgg')
import georasters as gr
```

will be great if matplotlib can be lazily imported

**Comment by ozak** [comment]
@DeoLeung was this the ``conda`` install? I know that ``matplotlib`` on ``OSX conda`` tends to have issues if one is not using ``pythonw``. Can you elaborate more on what you mean with ''lazily imported''.

**Comment by ozak** [comment]
I have done some research and it seems lazy imports can cause other problems. Since this is mostly an issue that can be worked around using ``pythonw`` or using one of the other backends like you did I think it may be best to let the user solve it in another way (at least for now).
