### ISSUE TITLE
Wrong bounds on multi-band raster

### ISSUE THREAD

**Issue by lucabaldassarre** [ozak/georasters#26]
I have a raster with 8 bands that I load via:
```
raster = '../../Data/21-Mar-2016_part1.tif'
data = gr.from_file(raster)
```
The data shape is (8, 3485, 3617).
The bounds I obtain via data.bounds is not correct because it does not use the correct shape size.

```
data.bounds
(-49.061416, -22.462534226398855, -48.72194693862317, -22.461815)
```
While

```
geot = data.geot
shape = data.shape
geot[3]+geot[5]*shape[1]
```
returns the correct value of -22.775128 instead of -22.462534226398855 and

`geot[0]+geot[1]*shape[2]`

returns the correct value of -48.709089 instead of -48.72194693862317.
Perhaps, the bounds method need to be modified as to be aware which axis corresponds to x and y and not to the band?

**Comment by ozak** [comment]
Can you share this file? I'll try to take a look and solve this today.

**Comment by lucabaldassarre** [comment]
The file is quite big (200mb), but the issue does not appear when using a single-band raster.

**Comment by ozak** [comment]
Ok. I am modifying the code so one can choose the band (at least in some parts), but it seems the main function used to load the data ``gdalnumeric.LoadFile`` does not have a way to choose the band. This may require a change to another function or package like ``rasterio``. I want to move towards using ``rasterio`` #3, but have not had the time.

**Comment by ozak** [comment]
If you have a smaller file you can share so I can play with it, it would be useful.

**Comment by lucabaldassarre** [comment]
I resampled my file, it is now 32mb.

[sample_image.tar.gz](https://github.com/ozak/georasters/files/1706351/sample_image.tar.gz)

**Comment by ozak** [comment]
I will close this and open an enhancement request for multiband rasters.
