### ISSUE TITLE
MemoryError when loading raster

### ISSUE THREAD

**Issue by lorenzori** [ozak/georasters#30]
first of all thank you for this library, looks very promising! 

I noticed an issue when loading a raster. If I do `gr.load_tiff(raster)` I get `MemoryError`.

If I load the same rater with `rasterio`  (`rasterio.open(raster)`) it loads fine.

The raster I am trying to load can be found [here](http://2016africalandcover20m.esrin.esa.int/).

**Comment by lorenzori** [comment]
ah it fails with gdal too. Ok maybe I just need to resize the raster :)

**Comment by ozak** [comment]
usually the ``MemoryError`` is caused by having too big a raster compared to your RAM. What size is your raster and RAM?

BTW, since you have been using ``rasterio`` would you be interested in helping implement ``load_from`` and ``to_file``  functions based on ``rasterio``?

**Comment by lorenzori** [comment]
as in `load_from`  a .tif file using rasterio?

**Comment by ozak** [comment]
Yes. I think it would be nice to have an API that would allow people to open and save various kinds of files. Then have specific commands for each type, as in ``geopandas`` or ``pandas``. I think once one moves this to ``rasterio`` creating reprojections and such may also be simple.

**Comment by lorenzori** [comment]
agreed, I had to exchange between different formats and it was a problem. Will take a look!
