### ISSUE TITLE
One-off error in map_pixel

### ISSUE THREAD

**Issue by maciejpfutzner** [ozak/georasters#36]
In [these lines](https://github.com/ozak/georasters/blob/e031ddf1c4bb0de00e05a830431ec67a5ad0d64a/georasters/georasters.py#L76-L77) `np.round` should be replaced by `np.floor`, otherwise half of the points get matched to the next pixel, which might not even exist in the data

**Comment by ozak** [comment]
That's what it used to do, but was causing one off errors in the use cases I tested. Can you provide an example of how it is causing issues now? Is it in the borders of the raster? I think it may need an additional if clause.

**Comment by ozak** [comment]
Indeed that is what I used to have and was my original reasoning. For some reason though it was messing up the ``union`` operation. I will check. Thanks for bringing this up.
