### ISSUE TITLE
Find value with map_pixel

### ISSUE THREAD

**Issue by KillianPremel** [ozak/georasters#38]
Hello everyone, 

I am quite new with georasters and I try to use it with ArcGIS to find the values of shading at specific cells.

The issue is that when I use map_pixel(x,y) I got a vector even if x,y are specific coordinates.
So I don't understand how map_pixel and what should be put for x and y.

The raster file is a raster created from a LAS file, with pipeline found at pdal.io. 

Regards

**Comment by ozak** [comment]
Were you able to resolve this? Does it work in ArcGIS? By any chance was this a multi band raster?
