### ISSUE TITLE
Updates for Pysal refactoring

### ISSUE THREAD

**Issue by apoorvalal** [ozak/georasters#40]
Are there any updates planned to support the commands that depend on pysal? Pysal 2.0 was a major refactor and modularized the library; e.g. `pysal.lat2w` (weight matrix) was moved to `pysal.lib.weights.lat2w` [link](https://pysal.readthedocs.io/en/latest/generated/pysal.lib.weights.lat2W.html#pysal.lib.weights.lat2W). As a result, running commands like `graster.pysal_G_local()` fail.

**Comment by ozak** [comment]
Yes. It is on the to do list. Any interest in helping out by contributing a PR for that?

**Comment by apoorvalal** [comment]
Sure, I've forked the repo and will try. Thanks for the hard work on this package; It has saved me from `rasterio`'s oddities several times.

**Comment by ozak** [comment]
Ok it seems for ``python>=3.6`` it is already using ``pysal>=2.0``. I think it should not be difficult to update. Basically check version of ``pysal``, then import accordingly.

**Comment by ozak** [comment]
@apoorvalal I just updated the code to import the correct functions for ``pysal>=2.0``.  If you can/want to test it and let me know if you have any issues that would be great.

**Comment by ozak** [comment]
I will close this for now. Testing still needed.
