### ISSUE TITLE
How to save the alligned rasters?

### ISSUE THREAD

**Issue by immuhammadadil** [ozak/georasters#43]
I have used the following command for raster allignment.
(alignedraster_o, alignedraster_a, GeoT_a) = gr.align_rasters(raster, raster2, how=np.mean)

Can anyone tell where are the aligned rasters stored? and how to save the aligned rasters?

**Comment by ozak** [comment]
``alignedraster_o`` and ``alignedraster_a`` are your aligned rasters. You can save them with the ``to_tiff`` function/property.

**Comment by immuhammadadil** [comment]
Thank you so much.

**Comment by immuhammadadil** [comment]
![savingtifferror](https://user-images.githubusercontent.com/18033345/66255156-c7d2bc00-e799-11e9-9c1a-de63cb775fa3.PNG)



HI,
I am getting the following error while saving the raster. Can you guide me to convert numpy array to raster?

Thanks
