### ISSUE TITLE
Issues in processing tiff generated by OpenDroneMap

### ISSUE THREAD

**Issue by immuhammadadil** [ozak/georasters#44]
I am having following issue in plotting the tiff generated by ODM:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-cfc655564ab6> in <module>
----> 1 data.plot()
      2 

~\Anaconda3\lib\site-packages\georasters\georasters.py in plot(self, **kwargs)
    502         Returns plot of raster data
    503         '''
--> 504         return plt.matshow(self.raster, **kwargs)
    505 
    506     def union(self, other):

~\Anaconda3\lib\site-packages\matplotlib\pyplot.py in matshow(A, fignum, **kwargs)
   2182         fig = figure(fignum, figsize=figaspect(A))
   2183         ax = fig.add_axes([0.15, 0.09, 0.775, 0.775])
-> 2184     im = ax.matshow(A, **kwargs)
   2185     sci(im)
   2186     return im

~\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in matshow(self, Z, **kwargs)
   7922               'aspect': 'equal',          # (already the imshow default)
   7923               **kwargs}
-> 7924         im = self.imshow(Z, **kw)
   7925         self.title.set_y(1.05)
   7926         self.xaxis.tick_top()

~\Anaconda3\lib\site-packages\matplotlib\__init__.py in inner(ax, data, *args, **kwargs)
   1587     def inner(ax, *args, data=None, **kwargs):
   1588         if data is None:
-> 1589             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1590 
   1591         bound = new_sig.bind(ax, *args, **kwargs)

~\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5658                               resample=resample, **kwargs)
   5659 
-> 5660         im.set_data(X)
   5661         im.set_alpha(alpha)
   5662         if im.get_clip_path() is None:

~\Anaconda3\lib\site-packages\matplotlib\image.py in set_data(self, A)
    681                 or self._A.ndim == 3 and self._A.shape[-1] in [3, 4]):
    682             raise TypeError("Invalid shape {} for image data"
--> 683                             .format(self._A.shape))
    684 
    685         if self._A.ndim == 3:

TypeError: Invalid shape (4, 5684, 6276) for image data

The properties of tiff are as follows:
![ODMMosaicPropertoes](https://user-images.githubusercontent.com/18033345/66272541-83701a80-e884-11e9-9263-6888e5a1e178.PNG)

**Comment by ozak** [comment]
You are trying to import and plot a multi-band raster. This is currently not supported (see #26)

**Comment by immuhammadadil** [comment]
Alright thanks.
I have used the rasterio to extract 1 raster band from tiff. Now it's working.
