### ISSUE TITLE
TIFF Alignment error

### ISSUE THREAD

**Issue by immuhammadadil** [ozak/georasters#45]
While aligning the tiff files generated by ODM of the same size. I am getting the following error. 
Any help regarding the requirements of tiff file would be of great help.
![ErrorinAllignment](https://user-images.githubusercontent.com/18033345/66291440-4dba4880-e8fb-11e9-86b5-be54961bb1d4.PNG)

Properties  of ODM mosaic are as follows:
![ODMMosaicPropertoes](https://user-images.githubusercontent.com/18033345/66291467-64f93600-e8fb-11e9-93dc-53531437cc65.PNG)

**Comment by ozak** [comment]
Is this the same multi-layer tif file?

**Comment by immuhammadadil** [comment]
Yes it was multilayer ruster. Thats why it was causing trouble.
I have used to rasterio to extract 1 band and now its working.
