### ISSUE TITLE
Alignment of tiffs is not accurate.

### ISSUE THREAD

**Issue by immuhammadadil** [ozak/georasters#50]
I have aligned two tiff files.But the alignment was not accurate.
PNGs of alligned rasters are attached below.

![alignedraster_a](https://user-images.githubusercontent.com/18033345/66667103-b2630380-ec6b-11e9-8e6f-0e27f16a8ec3.jpg)

![alignedraster_o](https://user-images.githubusercontent.com/18033345/66667106-b3943080-ec6b-11e9-8fac-ceec985709da.jpg)

**Comment by ozak** [comment]
Can you put the code and data you used so I can replicate on my end?

**Comment by immuhammadadil** [comment]
Here is code n data
https://drive.google.com/open?id=1b-wPrq3qqii5sBK5QRDXhCBJWqT6jr6b

**Comment by ozak** [comment]
@immuhammadadil I just updated the package. Could you check if you still have issues with version ``0.5.17``? Thanks.

**Comment by ozak** [comment]
I think the recent versions should address this issue. Check out ``0.5.20``. I am closing this, but reopen it if you still find issues.
