### ISSUE TITLE
questions about multiband rasters

### ISSUE THREAD

**Issue by DavidAnderson-USFS** [ozak/georasters#54]
I had a few questions about the Georasters Python package which I emailed to Omer Ozak.  

Where I ran into some questions is around multi band rasters.  I am doing some processing to create rasters by year.  I want to stack those rasters into a multi band raster to make the file management easier – just one file instead of dozens.  I can’t figure out how to create a multi band raster from a set of georaster objects. 
 
I am also wondering how to work with multi band rasters.  I loaded a multi band raster.  That worked find but I could not figure out how to access the individual bands.  I assumed that a pythonic/pandas syntax like my_raster[1] or my_raster[‘band_1’] would work but they didn’t.   Finally assuming I could get to each band how can the band name be accessed and changed?

His response
*Regarding your questions…sadly at the moment the package is really written to handle single bands. We added the ability to load a specific band, but it has not been expanded to work with real multband rasters. Given that in my own work I do not use them much, I never wrote it for that purpose. But as more and more users use the package and request the feature it may be added. I think it should not be too difficult to extend the package, but have not had time to work on this. If you are interested I always welcome help on the project.*

**Comment by ozak** [comment]
This is in the to-do list. See #26 #44
