### ISSUE TITLE
pip install georasters fails on GDAL

### ISSUE THREAD

**Issue by kkava** [ozak/georasters#55]
It seems like GDAL has changed and this package needs to be updated to account for that. A bit of digital decay has occurred. Or maybe someone can suggest a workaround for me? Thanks!

To recreate:
Windows 10 powershell / pip install georaster

    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python37-64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'X:\\Temp\\pip-install-zce_47at\\fiona\\setup.py'"'"'; __file__='"'"'X:\\Temp\\pip-install-zce_47at\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'X:\Temp\pip-install-zce_47at\fiona\pip-egg-info'
         cwd: X:\Temp\pip-install-zce_47at\fiona\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kkava** [comment]
On further inspection it seems like I have to first install GDAL which cannot be done through pip. If that is the case this issue can just be closed, because I haven't done that (and don't really want to - I like my code to remain as distributable and accessible as possible). Thanks again,
Kava

**Comment by ozak** [comment]
Indeed you need GDAL, but I think that is inescapable if you are doing GIS. So that should not be a major limitation in general. Luckily, ``conda`` makes it easy to share your code and your setup to ensure it works.

**Comment by kkava** [comment]
Hi Ömer,

thanks for the reply. I ended up finding the data I needed in a text file,
so I didn't have to try to deal with the inner workings of the geotiff
file. I'm working with the data from SEDAC, containing population
distributions, to model the spread of covid-19. It's pretty interesting.

-Kava
