### ISSUE TITLE
error in converting to and from Pandas

### ISSUE THREAD

**Issue by davidanderson-1701** [ozak/georasters#56]
Hello,
I am getting an error when trying to convert back and forth from Pandas.
I open the file like so:
states_gr = gr.from_file(state_class_file)
states_pd = states_gr.to_pandas()
... Do some pandas work on states_pd...
temp_raster = gr.from_pandas(states_pd,value='new_value',projection=Projection,geot=GeoT)

This gives me the error
ValueError: Index contains duplicate entries, cannot reshape

Data is here:
https://drive.google.com/open?id=1TwgMMEM3GRxc5yEz1MfRZPuuijnd9f-k

I have done this process in other code.  Not sure what the issue is with data.

**Comment by ozak** [comment]
Hi @davidanderson-1701, sorry I haven't had the time to look at your data (also I cannot access it since the link does not seem to allow anyone to access it), but I Imagine in your pandas work you are creating duplicate indices based on (lat, lon, or geometry). So converting back to a raster is impossible until you somehow aggregate those duplicates into one observation to be used. I'd suggest you check your index for duplications. Then figure out why those are there (could be that the same grid cell got duplicated in some spatial join or so?) and the how to deal with those. Aggregate by sum/mean/max/min? I hope this helps

**Comment by davidanderson-1701** [comment]
Omer,
Thanks for the reply.  I thought that I had the Google drive set up for
people to download.  I have attached the file here.  It is simple constant
raster created using ArcGIS.  I did not do any index manipulations.  I am
wanting to change the raster cell values while leaving the basic raster
spatial structure in place such as location, projection, etc.

**Comment by ozak** [comment]
@davidanderson-1701 it seems your file did not go through. What operations are you performing? Why do you go the ``pandas`` route? Seems you could just assign values to the underlying raster of the ``GeoRaster`` object, which is a simple ``numpy.MaskedArray``. If you are perfomring any geographic operations on the ``pandas`` dataframe that may be creating double indices?

**Comment by davidanderson-1701** [comment]
Here is the code that fails.  As I said there are no geographic or index
operations happening.
I went the pandas route as my initial forays into using the tools had
involved pandas due to its ease in manipulating the data and that I work
with the tool quite a bit.. I don't have a lot of experience in working
with numpy arrays.
I did end up doing as you suggested, working directly with the georasters
object, which was a easier.

import pandas as pd
import arcpy.sa as sa
import arcpy as ap

cell_size = 63.6149  # working in meters.  This will give 1 acre cell
num_rows = 100
num_cols = 100
x_lower = 385444
y_lower = 3888020
output_extent =
sa.Extent(x_lower,y_lower,x_lower+cell_size*num_rows,y_lower+cell_size*num_cols)
output_coordinate_system = 'NAD 1983 UTM Zone 13N'
epsgid = 26913
ap.env.outputCoordinateSystem = ap.SpatialReference(epsgid)

state_classes = {
'MCD:A_GFB':223,
'MCD:B_SSO':224,
'MCD:C_SMO':225,
'MCD:D_MOS':226,
'MCD:E_VOS':227,
'MCD:F_SSC':228,
'MCD:G_SMC':229,
'MCD:H_MCS':230,
'MCD:I_VCS':231,
'MCD:J_MOM':232,
'MCD:K_VOM':233,
'MCD:L_MCM':234,
'MCD:M_VCM':235,
'PP:N_UNC':298}

state_classes_to_include =
['MCD:G_SMC','MCD:H_MCS','MCD:I_VCS','MCD:J_MOM','MCD:K_VOM'] # a wag for
now
# pick a base class.  This will get the excess rows and cols in the case
that the space can't
# be evenly divided
state_class_file  =
r"E:\r3_analyst_work\STSim_testing\state_distribution.tif"
base_class = random.choice(states_classes_to_include)
states_raster_data =
sa.CreateConstantRaster(state_classes[base_class],"INTEGER",cell_size,output_extent)
states_raster_data.save(state_class_file)
no_data_val, xsize, ysize, GeoT, Projection, DataType =
gr.get_geo_info(state_class_file)

states_gr = gr.from_file(state_class_file)
states_pd = states_gr.to_pandas()

states_pd['new_value'] = states_pd.value
for i,name in enumerate(states_classes_to_include):
    row_min = i*size_rows
    row_max = (i+1) * size_rows - 1
    col_min = i*size_rows
    col_max = (i+1) * size_rows - 1
    states_pd.loc[((states_pd.row>=row_min) &  (states_pd.row<=row_max) &
(states_pd.col>=col_min) &
                             (states_pd.col<=col_max)),'new_value'] =
state_classes[name]

temp_raster =
gr.from_pandas(states_pd,value='new_value',projection=Projection,geot=GeoT)
temp_raster.to_tiff(state_class_file)

This step fails
temp_raster =
gr.from_pandas(states_pd,value='new_value',projection=Projection,geot=GeoT)

Just a suggestion that you might want to check things on your end.  I have
never had a problem with sending data either via google drive or directly
emailing.

**Comment by ozak** [comment]
Ok now I understand what you are doing and I think I know the issue. You have created multiple columns in the line 

```python
states_pd.loc[((states_pd.row>=row_min) &  (states_pd.row<=row_max) &
(states_pd.col>=col_min) &
                             (states_pd.col<=col_max)),'new_value'] =
state_classes[name]
```
but ``georasters`` doesn't know how to handle multiple band rasters and thus it cannot handle this (see #54). You would have to create the new raster using the original indices ``row   col     value             x             y`` and the ``new_value`` column. Something like

```python
temp_raster = gr.from_pandas(states_pd[['row', 'col', 'x', 'y', 'new_value']], value='new_value', projection=Projection, geot=GeoT)
```

should work I think.

**Comment by ozak** [comment]
Ok. It seems is is both what I referred to, but also it seems a previous change I had done is messing this up. I am correcting this and there should be a new version at some point today. Thanks for the patience and helping out. Let me know if after upgrading it works ok.

**Comment by ozak** [comment]
I will close this for now, since in my tests the correction seems to be working. But reopen it if that is not the case for you.

**Comment by davidanderson-1701** [comment]
Thanks for looking into the issue.  Glad there was a positive resolution.
