### ISSUE TITLE
Potential bug in aggregate function

### ISSUE THREAD

**Issue by pgr-me** [ozak/georasters#6]
Hello - I'm getting an UnboundLocalError: local variable 'raster2' referenced before assignment when I call the gr.aggregate function. Code is below and test dataset KEN.tif attached as zip (clipped version of SEDAC-CIESIN population density raster).

Is this an problem with my code or with the aggregate function?

Thanks!
```
import georasters as gr

raster = 'KEN.tif'
data = gr.from_file(raster)
NDV, xsize, ysize, GeoT, Projection, DataType = gr.get_geo_info(raster)
gr.aggregate(data,NDV,(10,10))
```

[KEN.tif.zip](https://github.com/ozak/georasters/files/501478/KEN.tif.zip)

**Comment by ozak** [comment]
Hi @pgr-me, thanks for pointing this out. I have just corrected the Github version...will update the pip version soon.

BTW, you should be running either
    # aggregate is defined on Numpy Masked Arrays
    gr.aggregate(data.raster,NDV,(10,10))

or better yet

   data.aggregate((10,10))

which will return a GeoRaster with all the correct info.

**Comment by ozak** [comment]
Ok..you should be able to install via pip also.

**Comment by pgr-me** [comment]
Excellent, data.aggregate((10,10)) worked. Thanks!
