### ISSUE TITLE
Error installing with pip on google colab

### ISSUE THREAD

**Issue by WHBSpeiser** [ozak/georasters#61]
Hi!

I have been trying to use georasters on Google Colab but every time I try to install it I get the error: "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output." 

Any suggestions?

Thanks!

**Comment by ozak** [comment]
Did you resolve the issue? can you share what happened?

**Comment by WHBSpeiser** [comment]
Yes! Sorry. Google colabs has an issue downloading rtrees which was creating an error with the pip install of georasters. The fix is to download rtrees separately before installing georasters via: 

!apt install libspatialindex-dev
!pip install rtree

**Comment by ozak** [comment]
Good tip!
