### ISSUE TITLE
ModuleNotFoundError: No module named 'gdalconst'

### ISSUE THREAD

**Issue by pessimo** [ozak/georasters#63]
after installation, when I import georasters in python, it gives me this error.
> File "/usr/local/lib/python3.9/site-packages/georasters/georasters.py", line 34, 
> in <module> from gdalconst import GA_ReadOnly
> ModuleNotFoundError: No module named 'gdalconst'

As far as I understand, we need to
> from osgeo import gdalconst

is this a bug?

**Comment by ozak** [comment]
This may be a new issue or just an installation issue. I have not tested on ``3.9``, but unless something changed in the underlying packages it uses, this should not happen. Can you provide more info about your install etc.?

**Comment by pessimo** [comment]
I got a macOS BIg Sur 11.0, and installed python 3.9

when installing georaster there's problem installing llvmlite, so I just point LLVM_CONFIG

> LLVM_CONFIG=/usr/local/opt/llvm@9/bin/llvm-config pip3 install georaster

and the installation finishes with no error.

after installation I upgrade gdal to 3.2.1 with brew, which, I guess, might be relevant to this error.

**Comment by ozak** [comment]
I think so too. It may be that gdal is not linking correctly? Because I doubt they changed the API between v3.0.4, which I have on my computer, and v3.2.1. Have you tried installing and upgrading gdal before installing georasters?

**Comment by pessimo** [comment]
Since my gdal was installed with brew, I tried 
> brew uninstall gdal
> pip3 uninstall georasters

and then reinstall gdal and georasters with
> brew install gdal
> pip3 install georasters

all the installation finishes with no error, but the error when import persists.
I'll try downgrade gdal to 3.0.1 manually latter.

**Comment by kharris91** [comment]
+1

## Versions:

OSX 10.15.7

```
pip freeze | grep -iE '(gdal|georasters)'
GDAL==3.2.1
georasters==0.5.22
```

## Repro

Tried with different installations of GDAL:

- From the [pre-built binaries](https://www.kyngchaos.com/software/frameworks/) of both 3.1 and 3.2
- From `brew` which installed 3.2.1

Both of the pre-built binaries ran into problems and brew seemed to work the best overall. The catch is that only the latest version (3.2.1) was available there - so downgrading wasn't an option. Didn't try to build from source.

Thanks to @pessimo for the tips above - had to use both the `llvm-config` tip (for the dependency) as well as the import fix. The import fix did it, and looking into the structure of `osgeo` package, this does look like a bug in `georasters`. Seems like georasters.py#L34 should be `from osgeo.gdalconst import GA_ReadOnly` - there is no top-level `gdalconst` package available.

**Comment by ozak** [comment]
Thanks @kharris91 and @pessimo for helping diagnose. Can you try with the updated install and let me know if this resolves the issue?

**Comment by pessimo** [comment]
@ozak  just come back to say, with the update of Fiona in April, it seems this issue is fixed, currently, my python3.9 environment can use georasters with no error.

**Comment by ozak** [comment]
Glad to hear. Although if you were reinstalling, it may have been the correction suggested by @kharris91 and implemented in https://github.com/ozak/georasters/commit/b0f7e7b388292c243902398c00f958aae8e17a8c. I'll close this issue now.
