### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by JavierParada** [ozak/georasters#64]
Do the GPS coordinates created from a raster obtained by applying data = gr.from_file(raster) represent the middle of the pixel or one of the sides? I couldn't find the answer in the documentation.

**Comment by ozak** [comment]
When you import it uses the information of the file (usually I think it should be the center). That is handled by one of the underlying packages ``georasters`` calls. The ``to_(geo)pandas`` function does use the top left corner (I have been planning to allow the option to choose, but have not had the time). I guess if you want to change the location (if you feel it is incorrect) is to change the ``geot`` by changing the location of the top-left coordinate.

**Comment by JavierParada** [comment]
Hello, I'm getting an error message when using the function **to_pandas()** . Any idea how to fix this? The function **to_geopandas()** works fine. Thanks!

<class 'georasters.georasters.GeoRaster'>
/usr/local/lib/python3.10/dist-packages/georasters/georasters.py:1467: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  df['x'] = df['geometry'].centroid.x
/usr/local/lib/python3.10/dist-packages/georasters/georasters.py:1468: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  df['y'] = df['geometry'].centroid.y
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py](https://cb1sfdb8lbf-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240318-060130_RC00_616776980#) in get_loc(self, key, method, tolerance)
   3801             try:
-> 3802                 return self._engine.get_loc(casted_key)
   3803             except KeyError as err:

7 frames
pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'geometry'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py](https://cb1sfdb8lbf-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240318-060130_RC00_616776980#) in get_loc(self, key, method, tolerance)
   3802                 return self._engine.get_loc(casted_key)
   3803             except KeyError as err:
-> 3804                 raise KeyError(key) from err
   3805             except TypeError:
   3806                 # If we have a listlike key, _check_indexing_error will raise

KeyError: 'geometry'

**Comment by ozak** [comment]
You are right. I just corrected and updated the code. The new version should work correctly. It is ready for pip install and the conda version should be up in a bit also. I will close this issue, but reopen it if there are still issues.
