### ISSUE TITLE
Merge many rasters

### ISSUE THREAD

**Issue by jozphlp** [ozak/georasters#68]
Does your packages allow to merge many tiles into one big raster file? Thanks

**Comment by ozak** [comment]
Do you mean creating a union of those tiles? I.e., a larger raster with the information of those tiles (similar to union of geometries in shape files). Then the answer is yes! That was one of the main reasons to write the package. You just use `union`. See the examples in [this notebook](https://econgrowth.github.io/notebooks/GIS%20with%20Python%202.ipynb). The use is simple:

```
#import a list of rasters into list_rasters

merged_list = gr.union(list_rasters)
```
