### ISSUE TITLE
tiff files larger than 500mb!! 

### ISSUE THREAD

**Issue by vinayk95** [ozak/georasters#69]

**Comment by vinayk95** [comment]
How do you work on a file that is larger than 500mb? I am getting a memory error when trying to do ".to_pandas" function.

**Comment by ozak** [comment]
I work normally with files over a couple of GB without any issues. Are you having issues loading or doing anything else? Or is it only when you try to convert to ``pandas``?

**Comment by vinayk95** [comment]
It was just converting to pandas dataframe. I think Pandas cant handle that big files right? So can we write that function directly to csv?

**Comment by ozak** [comment]
`pandas` should never have any issues with that either. I've worked with files orders of magnitude ladder in pana without any issues. What you computer's configuration?

**Comment by vinayk95** [comment]
I was trying to convert a multiple tiff files of 450 mb to one single csv file, but just for one 450 mb it gave me an error. have a 32gb ram, 2tb ssd. Also tried it in colab. Can we write directly to CSV, like using the writer object? I have been trying that as well, gives me an int subscriptable error

**Comment by vinayk95** [comment]
Plus I have more than 100 gb of raster files

**Comment by vinayk95** [comment]
I have an external harddrive of 18tb and I am trying to write the data in that

**Comment by ozak** [comment]
Strange. I'm not sure why you would have an issue. What's the ` shape` of each raster?

**Comment by ozak** [comment]
Just to clarify. You have the issue with any of your files? Or is there only one where you have the issue?
