### ISSUE TITLE
to_geopandas method, Polygon not defined

### ISSUE THREAD

**Issue by debboutr** [ozak/georasters#7]
was just playing around with this package, really cool!  Anyway I noticed there should be an import in the georasters.py script for the shapely.geometry Polygon when using the method to_geopandas(). I tested it out and seemed to work fine when added.

from shapely.geometry import Polygon

add the above to the georasters.py script to eliminate the error:

NameError: ("global name 'Polygon' is not defined", u'occurred at index 0')

I am rather new to python, let me know if I'm incorrect here, thanks!

~rickD

**Comment by ozak** [comment]
@debboutr thanks for noticing! Indeed I think you are 100% right.

**Comment by ozak** [comment]
Implemented in #8
