### ISSUE TITLE
problem with to_tiff

### ISSUE THREAD

**Issue by pooranasaviour** [ozak/georasters#70]
I loaded a tiff file edited the values and then tried to export the edited values as a new tiff file using to_tiff but I get an error message saying that 'NoneType' object has no attribute 'ExportToWkt'. Am I missing something related to projection here?

**Comment by ozak** [comment]
Could you post the code? Think you're missing the data type.

**Comment by pooranasaviour** [comment]
Thanks for your reply. Here are the last two lines where I have the issue. I am new with this and I do not know if I missed some important info while using from_pandas. When I created newtiff I got no error message. Only when exporting using to_tiff I get the error message:
newtiff = gr.from_pandas(ws_df, value ='need', x='x', y='y')
newtiff.to_tiff('Folderlink/newtiff.tif')

**Comment by ozak** [comment]
So it is definitely that you are missing the ``datatype``.  The function requires you to pass the information for the GeoTiff

```python
from_pandas(df, value='value', x='x', y='y', cellx=None, celly=None, xmin=None, ymax=None,
                geot=None, nodata_value=None, projection=None, datatype=None)
```

so you could just pass those values from the original raster you imported (assuming the only thing that changed are values but not geographical info. So, you could write

```python

newtiff = gr.from_pandas(ws_df, value ='need', x='x', y='y', geot=oldtiff.geot, projection=oldtiff.projection, datatype=oldtiff.datatype, )
```

you can add the other info also if needed.

**Comment by pooranasaviour** [comment]
Thank you so much! It worked. Have a nice day!
